version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      - image: mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: circle_test
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a6:70:0a:11:95:5e:d0:a6:eb:0e:9b:84:ea:29:96:23"
      - checkout
      - run:
          name: Install
          command: |
            npm install
            npm install sequelize@^4.42.0 --no-save
      - run:
          name: Compile
          command: |
            npm run build
            npm run lint
      - run:
          name: Test
          command: |
            npm test
            npm run coverage
            npm run codecov
      - run:
          name: Publish
          command: |
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCI
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm run lock
            if test "$CIRCLE_BRANCH" = "master"; then npm run cd; else git push origin $CIRCLE_BRANCH; fi
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
